spring.application.name=subscription_billind_b2b

##Postgres properties##
spring.datasource.url=jdbc:postgresql://postgres-db:5432/billing_db
spring.datasource.username=root
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
##------------------##

##Liquibase properties##
spring.liquibase.enabled=true
